services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: pharmtrack_gateway
    command: gunicorn pharmtrack_gateway.wsgi:application --bind 0.0.0.0:8000 --reload

    env_file:
      - .env

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    networks:
      - pharmtrack_net

    restart: unless-stopped

networks:
  pharmtrack_net:
    external: true
