apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: pharmtrack
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DB_NAME: "gateway_db"
  DB_USER: "postgres"
  DB_HOST: "postgres-gateway.pharmtrack.svc.cluster.local"
  DB_PORT: "5432"
  REDIS_URL: "redis://:$(REDIS_PASSWORD)@redis.pharmtrack.svc.cluster.local:6379/0"
  RABBITMQ_HOST: "rabbitmq.pharmtrack.svc.cluster.local"
  RABBITMQ_VHOST: "pharmtrack"
