apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pharmtrack
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - migrate-job.yaml
