# Generated by Django 5.0.4 on 2026-07-07 10:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('notification_type', models.CharField(choices=[('delivery_assigned', 'Delivery Assigned'), ('delivery_scanned', 'Delivery Scanned'), ('delivery_completed', 'Delivery Completed'), ('delivery_cancelled', 'Delivery Cancelled'), ('delivery_status_changed', 'Status Changed'), ('user_login', 'User Login'), ('general', 'General')], default='general', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
