version: "3.9"

services:
  email-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: pharmtrack_email

    env_file:
      - .env

    ports:
      - "8003:8003"

    volumes:
      - .:/app

    networks:
      - pharmtrack_net

    restart: unless-stopped

networks:
  pharmtrack_net:
    external: true
